[build]
target = "riscv32i-unknown-none-elf"

[target.riscv32i-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.x",   # linker script to run..
    "-C", "opt-level=s",         # optimize option (s-size)
]
